<?php 
require_once("../includes/head.inc.php");
require("../includes/serviceJoueur.php");
require("../includes/serviceMatchs.php");
require("../includes/serviceListesDiverses.php");
require("../includes/serviceDTN.php");
if(!$sesUser["idAdmin"])
{
	header("location: index.php?ErrorMsg=Session Expire");
}
?>
<link href="../css/ht2.css" rel="stylesheet" type="text/css">
<script language="JavaScript" src="../includes/javascript/navigation.js"></script>
<?php
switch($sesUser["idNiveauAcces"]){
		case "1":
		require("../menu/menuAdmin.php");
		break;
		
		case "2":
		require("../menu/menuSuperviseur.php");
		break;


		case "3":
		require("../menu/menuDTN.php");
		break;
		
		case "4":
		require("../menu/menuCoach.php");
		break;
		
		default;
		break;

}
?>
<br><br>
<table border="0" cellpadding="0" cellspacing="0">
    <tr> 
      <td valign="middle"><b>Cette page contient la liste de tous les pays, ainsi que leur ID, le nombre de managers, d'équipes, de secondes et troisi&egrave;mes équipes.
	  <br>Elle contient également les dates & horaires pour les matchs de ligues, de coupes (ou amicaux), ainsi que pour les mises &agrave; jour de l'entrainement et les mises &agrave; jour financières, pour chaque pays.</b>
      <br><br>Les données présentées ici sont issues de <a style="color:black" href="http://fcclogo.kaoztribe.net/Countries.php" target="_blank">ce site</a>.       
	  <br><br>
	  <br><i>Dernière mise à jour : 11/08/2019</i></td>
	</tr>
</table> 


<br><br><br><br>
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
<tr bgcolor="#EFEFEF"><th>ID Ligue</th><th>Nom</th><th>Nb<br>niveaux</th><th>#Managers</th><th>#Equipes</th><th>2ndes /3e<br>Equipes</th><th>Match<br>de ligue</th><th>Match de <br>Coupe/amical</th><th>Entrainement</th><th>MaJ <br>financi&egrave;re</th></tr>
<tr><td align=center>1</td><td align=center> Sverige</td><td align=center>6</td><td align=center>6377</td><td align=center>6633</td><td align=center>256</td><td align=center>Dim 10:00</td><td align=center>Mer 19:00</td><td align=center>Jeu 22:00</td><td align=center>Dim 00:10</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>2</td><td align=center> England</td><td align=center>6</td><td align=center>2292</td><td align=center>2567</td><td align=center>275</td><td align=center>Dim 18:00</td><td align=center>Mar 21:00</td><td align=center>Jeu 21:00</td><td align=center>Ven 21:00</td></tr>
<tr><td align=center>3</td><td align=center> Deutschland</td><td align=center>7</td><td align=center>16108</td><td align=center>16602</td><td align=center>494</td><td align=center>Sam 18:00</td><td align=center>Mar 18:00</td><td align=center>Ven 00:30</td><td align=center>Sam 00:10</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>4</td><td align=center> Italia</td><td align=center>8</td><td align=center>21014</td><td align=center>21265</td><td align=center>251</td><td align=center>Sam 12:00</td><td align=center>Mar 19:00</td><td align=center>Jeu 23:45</td><td align=center>Sam 02:00</td></tr>
<tr><td align=center>5</td><td align=center> France</td><td align=center>6</td><td align=center>8639</td><td align=center>8854</td><td align=center>215</td><td align=center>Sam 21:00</td><td align=center>Mer 15:00</td><td align=center>Ven 05:15</td><td align=center>Sam 02:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>6</td><td align=center> México</td><td align=center>5</td><td align=center>1355</td><td align=center>1404</td><td align=center>49</td><td align=center>Dim 17:30</td><td align=center>Jeu 02:00</td><td align=center>Ven 03:45</td><td align=center>Dim 01:00</td></tr>
<tr><td align=center>7</td><td align=center> Argentina</td><td align=center>6</td><td align=center>6330</td><td align=center>6399</td><td align=center>69</td><td align=center>Dim 21:40</td><td align=center>Jeu 01:30</td><td align=center>Ven 06:00</td><td align=center>Sam 03:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>8</td><td align=center> USA</td><td align=center>5</td><td align=center>1965</td><td align=center>2195</td><td align=center>230</td><td align=center>Lun 01:00</td><td align=center>Jeu 01:00</td><td align=center>Ven 03:30</td><td align=center>Dim 01:30</td></tr>
<tr><td align=center>9</td><td align=center> Norge</td><td align=center>6</td><td align=center>2520</td><td align=center>2709</td><td align=center>189</td><td align=center>Sam 16:00</td><td align=center>Mer 16:00</td><td align=center>Jeu 20:30</td><td align=center>Ven 23:00</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>11</td><td  align=center> Danmark</td><td align=center>6</td><td align=center>4083</td><td align=center>4237</td><td align=center>154</td><td align=center>Dim 16:00</td><td align=center>Mer 16:30</td><td align=center>Ven 03:00</td><td align=center>Dim 01:20</td></tr>
<tr><td align=center>12</td><td  align=center> Suomi</td><td align=center>6</td><td align=center>6036</td><td align=center>6166</td><td align=center>130</td><td align=center>Sam 20:00</td><td align=center>Mar 20:00</td><td align=center>Ven 05:00</td><td align=center>Sam 00:20</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>14</td><td  align=center> Nederland</td><td align=center>6</td><td align=center>8261</td><td align=center>8443</td><td align=center>182</td><td align=center>Dim 20:00</td><td align=center>Mer 17:00</td><td align=center>Ven 01:05</td><td align=center>Dim 02:00</td></tr>
<tr><td align=center>15</td><td  align=center> Oceania</td><td align=center>5</td><td align=center>905</td><td align=center>1013</td><td align=center>108</td><td align=center>Dim 04:00</td><td align=center>Mer 04:00</td><td align=center>Ven 04:00</td><td align=center>Sam 00:10</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>16</td><td  align=center> Brasil</td><td align=center>6</td><td align=center>3202</td><td align=center>3277</td><td align=center>75</td><td align=center>Lun 00:00</td><td align=center>Jeu 00:00</td><td align=center>Ven 00:05</td><td align=center>Dim 01:45</td></tr>
<tr><td align=center>17</td><td  align=center> Canada</td><td align=center>5</td><td align=center>689</td><td align=center>805</td><td align=center>116</td><td align=center>Dim 23:00</td><td align=center>Mer 23:00</td><td align=center>Ven 07:30</td><td align=center>Dim 02:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>18</td><td  align=center> Chile</td><td align=center>6</td><td align=center>4545</td><td align=center>4611</td><td align=center>66</td><td align=center>Dim 22:40</td><td align=center>Mer 22:40</td><td align=center>Ven 08:15</td><td align=center>Dim 03:30</td></tr>
<tr><td align=center>19</td><td  align=center> Colombia</td><td align=center>5</td><td align=center>1796</td><td align=center>1834</td><td align=center>38</td><td align=center>Lun 00:50</td><td align=center>Jeu 00:50</td><td align=center>Ven 06:30</td><td align=center>Dim 03:40</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>20</td><td  align=center> India</td><td align=center>5</td><td align=center>165</td><td align=center>187</td><td align=center>22</td><td align=center>Dim 08:15</td><td align=center>Mer 06:00</td><td align=center>Ven 06:05</td><td align=center>Sam 04:44</td></tr>
<tr><td align=center>21</td><td  align=center> Ireland</td><td align=center>5</td><td align=center>286</td><td align=center>432</td><td align=center>146</td><td align=center>Dim 16:30</td><td align=center>Mer 20:15</td><td align=center>Ven 05:45</td><td align=center>Sam 01:45</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>22</td><td  align=center> Nippon</td><td align=center>5</td><td align=center>179</td><td align=center>255</td><td align=center>76</td><td align=center>Dim 04:15</td><td align=center>Mer 02:30</td><td align=center>Ven 04:15</td><td align=center>Sam 03:15</td></tr>
<tr><td align=center>23</td><td  align=center> Perú</td><td align=center>5</td><td align=center>1327</td><td align=center>1356</td><td align=center>29</td><td align=center>Lun 00:45</td><td align=center>Jeu 02:15</td><td align=center>Ven 05:30</td><td align=center>Dim 02:25</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>24</td><td  align=center> Polska</td><td align=center>7</td><td align=center>14783</td><td align=center>14870</td><td align=center>87</td><td align=center>Dim 09:00</td><td align=center>Mer 18:00</td><td align=center>Ven 02:30</td><td align=center>Sam 23:45</td></tr>
<tr><td align=center>25</td><td  align=center> Portugal</td><td align=center>6</td><td align=center>5927</td><td align=center>5999</td><td align=center>72</td><td align=center>Sam 21:45</td><td align=center>Mer 21:45</td><td align=center>Jeu 19:00</td><td align=center>Sam 01:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>26</td><td  align=center> Scotland</td><td align=center>5</td><td align=center>299</td><td align=center>487</td><td align=center>188</td><td align=center>Sam 17:30</td><td align=center>Mer 11:30</td><td align=center>Jeu 18:00</td><td align=center>Ven 23:35</td></tr>
<tr><td align=center>27</td><td  align=center> South Africa</td><td align=center>4</td><td align=center>104</td><td align=center>203</td><td align=center>99</td><td align=center>Dim 09:30</td><td align=center>Mer 21:30</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:27</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>28</td><td  align=center> Uruguay</td><td align=center>5</td><td align=center>1220</td><td align=center>1253</td><td align=center>33</td><td align=center>Lun 00:30</td><td align=center>Jeu 00:30</td><td align=center>Jeu 23:00</td><td align=center>Dim 03:41</td></tr>
<tr><td align=center>29</td><td  align=center> Venezuela</td><td align=center>5</td><td align=center>1016</td><td align=center>1037</td><td align=center>21</td><td align=center>Dim 23:30</td><td align=center>Mer 23:30</td><td align=center>Ven 06:15</td><td align=center>Dim 03:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>30</td><td  align=center> Hanguk</td><td align=center>5</td><td align=center>140</td><td align=center>160</td><td align=center>20</td><td align=center>Dim 04:45</td><td align=center>Mer 02:00</td><td align=center>Ven 04:45</td><td align=center>Sam 04:40</td></tr>
<tr><td align=center>31</td><td  align=center> Prathet Thai</td><td align=center>5</td><td align=center>116</td><td align=center>160</td><td align=center>44</td><td align=center>Dim 05:30</td><td align=center>Mer 05:30</td><td align=center>Ven 04:20</td><td align=center>Sam 02:20</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>32</td><td  align=center> Türkiye</td><td align=center>6</td><td align=center>4393</td><td align=center>4415</td><td align=center>22</td><td align=center>Dim 15:00</td><td align=center>Mer 08:00</td><td align=center>Jeu 16:06</td><td align=center>Sam 04:30</td></tr>
<tr><td align=center>33</td><td  align=center> Misr</td><td align=center>5</td><td align=center>67</td><td align=center>95</td><td align=center>28</td><td align=center>Sam 10:50</td><td align=center>Mar 18:50</td><td align=center>Jeu 04:07</td><td align=center>Ven 15:07</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>34</td><td  align=center> China</td><td align=center>5</td><td align=center>1336</td><td align=center>1378</td><td align=center>42</td><td align=center>Sam 07:00</td><td align=center>Mer 07:00</td><td align=center>Jeu 14:30</td><td align=center>Ven 22:30</td></tr>
<tr><td align=center>35</td><td  align=center> Rossiya</td><td align=center>5</td><td align=center>1171</td><td align=center>1212</td><td align=center>41</td><td align=center>Dim 08:30</td><td align=center>Mer 08:30</td><td align=center>Jeu 18:30</td><td align=center>Sam 23:40</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>36</td><td  align=center> España</td><td align=center>7</td><td align=center>14601</td><td align=center>14816</td><td align=center>215</td><td align=center>Sam 14:00</td><td align=center>Mer 12:00</td><td align=center>Ven 01:00</td><td align=center>Sam 01:00</td></tr>
<tr><td align=center>37</td><td  align=center> România</td><td align=center>6</td><td align=center>7912</td><td align=center>8000</td><td align=center>88</td><td align=center>Sam 10:00</td><td align=center>Mer 10:00</td><td align=center>Jeu 21:15</td><td align=center>Ven 23:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>38</td><td  align=center> Ísland</td><td align=center>4</td><td align=center>124</td><td align=center>297</td><td align=center>173</td><td align=center>Dim 19:30</td><td align=center>Mer 20:45</td><td align=center>Ven 06:45</td><td align=center>Sam 23:35</td></tr>
<tr><td align=center>39</td><td  align=center> Österreich</td><td align=center>6</td><td align=center>2545</td><td align=center>2686</td><td align=center>141</td><td align=center>Dim 09:30</td><td align=center>Mer 09:30</td><td align=center>Ven 07:00</td><td align=center>Sam 23:52</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>44</td><td  align=center> Belgium</td><td align=center>6</td><td align=center>7154</td><td align=center>7310</td><td align=center>156</td><td align=center>Dim 13:00</td><td align=center>Mer 13:00</td><td align=center>Ven 01:00</td><td align=center>Dim 00:25</td></tr>
<tr><td align=center>45</td><td  align=center> Malaysia</td><td align=center>5</td><td align=center>150</td><td align=center>165</td><td align=center>15</td><td align=center>Dim 05:00</td><td align=center>Mer 05:00</td><td align=center>Ven 08:00</td><td align=center>Sam 01:50</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>46</td><td  align=center> Schweiz</td><td align=center>7</td><td align=center>10499</td><td align=center>10997</td><td align=center>498</td><td align=center>Sam 17:00</td><td align=center>Mer 10:30</td><td align=center>Jeu 23:15</td><td align=center>Sam 02:15</td></tr>
<tr><td align=center>47</td><td  align=center> Singapore</td><td align=center>5</td><td align=center>163</td><td align=center>187</td><td align=center>24</td><td align=center>Dim 04:30</td><td align=center>Mer 04:30</td><td align=center>Ven 00:15</td><td align=center>Sam 03:27</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>50</td><td  align=center> Hellas</td><td align=center>5</td><td align=center>1894</td><td align=center>1926</td><td align=center>32</td><td align=center>Sam 11:00</td><td align=center>Mer 09:45</td><td align=center>Jeu 17:15</td><td align=center>Ven 23:25</td></tr>
<tr><td align=center>51</td><td  align=center> Magyarország</td><td align=center>6</td><td align=center>4770</td><td align=center>4830</td><td align=center>60</td><td align=center>Sam 15:30</td><td align=center>Mer 09:45</td><td align=center>Jeu 17:45</td><td align=center>Ven 23:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>52</td><td  align=center> Ceská rep.</td><td align=center>6</td><td align=center>4304</td><td align=center>4390</td><td align=center>86</td><td align=center>Sam 11:30</td><td align=center>Mer 14:00</td><td align=center>Jeu 17:30</td><td align=center>Ven 23:30</td></tr>
<tr><td align=center>53</td><td  align=center> Latvija</td><td align=center>5</td><td align=center>1050</td><td align=center>1084</td><td align=center>34</td><td align=center>Sam 11:45</td><td align=center>Mer 13:45</td><td align=center>Jeu 18:45</td><td align=center>Ven 23:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>54</td><td  align=center> Indonesia</td><td align=center>5</td><td align=center>253</td><td align=center>274</td><td align=center>21</td><td align=center>Sam 09:00</td><td align=center>Mer 07:45</td><td align=center>Jeu 17:00</td><td align=center>Ven 23:00</td></tr>
<tr><td align=center>55</td><td  align=center> Pilipinas</td><td align=center>4</td><td align=center>44</td><td align=center>114</td><td align=center>70</td><td align=center>Dim 06:15</td><td align=center>Mer 03:30</td><td align=center>Jeu 14:15</td><td align=center>Sam 03:21</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>56</td><td  align=center> Eesti</td><td align=center>5</td><td align=center>887</td><td align=center>923</td><td align=center>36</td><td align=center>Sam 11:15</td><td align=center>Mer 12:15</td><td align=center>Jeu 18:15</td><td align=center>Ven 23:45</td></tr>
<tr><td align=center>57</td><td  align=center> Srbija</td><td align=center>5</td><td align=center>1343</td><td align=center>1360</td><td align=center>17</td><td align=center>Sam 12:45</td><td align=center>Mer 12:45</td><td align=center>Jeu 16:30</td><td align=center>Ven 23:20</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>58</td><td  align=center> Hrvatska</td><td align=center>5</td><td align=center>1733</td><td align=center>1765</td><td align=center>32</td><td align=center>Sam 13:45</td><td align=center>Mer 08:45</td><td align=center>Jeu 16:45</td><td align=center>Ven 23:20</td></tr>
<tr><td align=center>59</td><td  align=center> Hong Kong</td><td align=center>5</td><td align=center>148</td><td align=center>181</td><td align=center>33</td><td align=center>Sam 08:30</td><td align=center>Mer 11:00</td><td align=center>Jeu 13:30</td><td align=center>Ven 22:45</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>60</td><td  align=center> Chin. Taipei</td><td align=center>5</td><td align=center>90</td><td align=center>120</td><td align=center>30</td><td align=center>Sam 05:00</td><td align=center>Mer 03:00</td><td align=center>Jeu 15:30</td><td align=center>Ven 22:16</td></tr>
<tr><td align=center>61</td><td  align=center> Cymru</td><td align=center>5</td><td align=center>74</td><td align=center>169</td><td align=center>95</td><td align=center>Sam 21:30</td><td align=center>Mar 21:30</td><td align=center>Jeu 15:30</td><td align=center>Ven 21:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>62</td><td  align=center> Bulgaria</td><td align=center>5</td><td align=center>1939</td><td align=center>1962</td><td align=center>23</td><td align=center>Sam 13:25</td><td align=center>Mar 21:15</td><td align=center>Jeu 15:30</td><td align=center>Ven 22:15</td></tr>
<tr><td align=center>63</td><td  align=center> Israel</td><td align=center>6</td><td align=center>2444</td><td align=center>2490</td><td align=center>46</td><td align=center>Sam 10:30</td><td align=center>Mar 20:30</td><td align=center>Jeu 15:30</td><td align=center>Ven 22:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>64</td><td  align=center> Slovenija</td><td align=center>5</td><td align=center>1233</td><td align=center>1253</td><td align=center>20</td><td align=center>Sam 13:20</td><td align=center>Mar 19:30</td><td align=center>Jeu 15:30</td><td align=center>Ven 22:17</td></tr>
<tr><td align=center>66</td><td  align=center> Lietuva</td><td align=center>5</td><td align=center>1249</td><td align=center>1268</td><td align=center>19</td><td align=center>Sam 15:20</td><td align=center>Mer 19:20</td><td align=center>Jeu 17:30</td><td align=center>Ven 23:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>67</td><td  align=center> Slovensko</td><td align=center>5</td><td align=center>1875</td><td align=center>1925</td><td align=center>50</td><td align=center>Sam 15:25</td><td align=center>Mar 19:25</td><td align=center>Jeu 17:30</td><td align=center>Ven 23:30</td></tr>
<tr><td align=center>68</td><td  align=center> Ukraina</td><td align=center>5</td><td align=center>687</td><td align=center>704</td><td align=center>17</td><td align=center>Dim 09:45</td><td align=center>Mer 08:15</td><td align=center>Jeu 18:30</td><td align=center>Sam 23:50</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>69</td><td  align=center> Bosna i Herc</td><td align=center>5</td><td align=center>818</td><td align=center>833</td><td align=center>15</td><td align=center>Sam 13:30</td><td align=center>Mer 14:15</td><td align=center>Jeu 16:30</td><td align=center>Ven 23:20</td></tr>
<tr><td align=center>70</td><td  align=center> Vi?t Nam</td><td align=center>5</td><td align=center>236</td><td align=center>253</td><td align=center>17</td><td align=center>Sam 08:00</td><td align=center>Mer 05:15</td><td align=center>Jeu 17:15</td><td align=center>Ven 22:30</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>71</td><td  align=center> Pakistan</td><td align=center>4</td><td align=center>40</td><td align=center>86</td><td align=center>46</td><td align=center>Dim 07:30</td><td align=center>Mer 06:15</td><td align=center>Ven 06:07</td><td align=center>Sam 02:22</td></tr>
<tr><td align=center>72</td><td  align=center> Paraguay</td><td align=center>5</td><td align=center>233</td><td align=center>261</td><td align=center>28</td><td align=center>Sam 23:15</td><td align=center>Mar 23:15</td><td align=center>Jeu 09:35</td><td align=center>Ven 23:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>73</td><td  align=center> Ecuador</td><td align=center>4</td><td align=center>146</td><td align=center>212</td><td align=center>66</td><td align=center>Sam 23:45</td><td align=center>Mar 23:45</td><td align=center>Jeu 09:35</td><td align=center>Ven 23:45</td></tr>
<tr><td align=center>74</td><td  align=center> Bolivia</td><td align=center>5</td><td align=center>348</td><td align=center>371</td><td align=center>23</td><td align=center>Sam 22:45</td><td align=center>Mar 22:45</td><td align=center>Jeu 09:40</td><td align=center>Ven 22:45</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>75</td><td  align=center> Nigeria</td><td align=center>4</td><td align=center>72</td><td align=center>146</td><td align=center>74</td><td align=center>Dim 18:45</td><td align=center>Mer 11:45</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:33</td></tr>
<tr><td align=center>76</td><td  align=center> Føroyar</td><td align=center>5</td><td align=center>88</td><td align=center>188</td><td align=center>100</td><td align=center>Dim 16:45</td><td align=center>Mer 16:45</td><td align=center>Ven 06:42</td><td align=center>Sam 23:32</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>77</td><td  align=center> Al Maghrib</td><td align=center>5</td><td align=center>93</td><td align=center>113</td><td align=center>20</td><td align=center>Dim 15:25</td><td align=center>Mer 20:50</td><td align=center>Jeu 13:15</td><td align=center>Dim 01:12</td></tr>
<tr><td align=center>79</td><td  align=center> Saudi Arabia</td><td align=center>5</td><td align=center>29</td><td align=center>72</td><td align=center>43</td><td align=center>Dim 16:20</td><td align=center>Mer 16:20</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>80</td><td  align=center> Tounes</td><td align=center>5</td><td align=center>103</td><td align=center>118</td><td align=center>15</td><td align=center>Dim 16:15</td><td align=center>Mer 16:45</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:47</td></tr>
<tr><td align=center>81</td><td  align=center> Costa Rica</td><td align=center>4</td><td align=center>112</td><td align=center>184</td><td align=center>72</td><td align=center>Dim 23:45</td><td align=center>Mer 23:45</td><td align=center>Ven 07:45</td><td align=center>Dim 03:33</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>83</td><td  align=center> U.A.E.</td><td align=center>5</td><td align=center>45</td><td align=center>98</td><td align=center>53</td><td align=center>Dim 11:50</td><td align=center>Mer 18:45</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:49</td></tr>
<tr><td align=center>84</td><td  align=center> Lëtzebuerg</td><td align=center>4</td><td align=center>144</td><td align=center>245</td><td align=center>101</td><td align=center>Dim 14:45</td><td align=center>Mer 14:45</td><td align=center>Ven 04:40</td><td align=center>Sam 23:39</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>85</td><td  align=center> Iran</td><td align=center>5</td><td align=center>1752</td><td align=center>1762</td><td align=center>10</td><td align=center>Dim 15:45</td><td align=center>Mer 15:45</td><td align=center>Ven 06:06</td><td align=center>Sam 03:23</td></tr>
<tr><td align=center>88</td><td  align=center> Rep. Dom.</td><td align=center>3</td><td align=center>49</td><td align=center>121</td><td align=center>72</td><td align=center>Dim 23:15</td><td align=center>Mer 23:15</td><td align=center>Ven 00:50</td><td align=center>Dim 03:25</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>89</td><td  align=center> Cyprus</td><td align=center>5</td><td align=center>141</td><td align=center>156</td><td align=center>15</td><td align=center>Sam 20:15</td><td align=center>Mar 20:15</td><td align=center>Jeu 17:15</td><td align=center>Ven 23:25</td></tr>
<tr><td align=center>91</td><td  align=center> Belarus</td><td align=center>5</td><td align=center>266</td><td align=center>273</td><td align=center>7</td><td align=center>Dim 10:15</td><td align=center>Mer 09:15</td><td align=center>Jeu 18:30</td><td align=center>Dim 00:44</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>93</td><td  align=center> N. Ireland</td><td align=center>4</td><td align=center>58</td><td align=center>146</td><td align=center>88</td><td align=center>Sam 22:15</td><td align=center>Mar 22:15</td><td align=center>Jeu 15:30</td><td align=center>Ven 22:15</td></tr>
<tr><td align=center>94</td><td  align=center> Jamaica</td><td align=center>4</td><td align=center>22</td><td align=center>140</td><td align=center>118</td><td align=center>Dim 22:15</td><td align=center>Mer 22:15</td><td align=center>Ven 01:45</td><td align=center>Dim 03:43</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>95</td><td  align=center> Kenya</td><td align=center>4</td><td align=center>33</td><td align=center>114</td><td align=center>81</td><td align=center>Dim 12:45</td><td align=center>Mer 11:15</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:44</td></tr>
<tr><td align=center>96</td><td  align=center> Panamá</td><td align=center>5</td><td align=center>129</td><td align=center>155</td><td align=center>26</td><td align=center>Lun 00:16</td><td align=center>Jeu 00:15</td><td align=center>Ven 00:45</td><td align=center>Dim 03:31</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>97</td><td  align=center> S Makedonija</td><td align=center>5</td><td align=center>154</td><td align=center>163</td><td align=center>9</td><td align=center>Sam 12:15</td><td align=center>Mer 10:15</td><td align=center>Jeu 16:30</td><td align=center>Ven 23:20</td></tr>
<tr><td align=center>98</td><td  align=center> Shqipëria</td><td align=center>5</td><td align=center>142</td><td align=center>160</td><td align=center>18</td><td align=center>Sam 16:45</td><td align=center>Mar 20:45</td><td align=center>Jeu 16:30</td><td align=center>Ven 23:20</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>99</td><td  align=center> Honduras</td><td align=center>4</td><td align=center>40</td><td align=center>95</td><td align=center>55</td><td align=center>Lun 01:15</td><td align=center>Jeu 01:15</td><td align=center>Ven 03:45</td><td align=center>Dim 03:28</td></tr>
<tr><td align=center>100</td><td align=center> El Salvador</td><td align=center>4</td><td align=center>26</td><td align=center>81</td><td align=center>55</td><td align=center>Lun 01:45</td><td align=center>Jeu 01:45</td><td align=center>Ven 03:50</td><td align=center>Dim 03:10</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>101</td><td align=center> Malta</td><td align=center>5</td><td align=center>185</td><td align=center>256</td><td align=center>71</td><td align=center>Dim 19:15</td><td align=center>Mer 17:15</td><td align=center>Ven 04:25</td><td align=center>Sam 02:00</td></tr>
<tr><td align=center>102</td><td align=center> Kyrgyz Rep</td><td align=center>3</td><td align=center>20</td><td align=center>80</td><td align=center>60</td><td align=center>Dim 07:30</td><td align=center>Mer 07:30</td><td align=center>Ven 06:03</td><td align=center>Sam 02:23</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>103</td><td align=center> Moldova</td><td align=center>5</td><td align=center>224</td><td align=center>250</td><td align=center>26</td><td align=center>Dim 17:45</td><td align=center>Mer 17:45</td><td align=center>Jeu 18:30</td><td align=center>Dim 00:54</td></tr>
<tr><td align=center>104</td><td align=center> Sakartvelo</td><td align=center>5</td><td align=center>448</td><td align=center>461</td><td align=center>13</td><td align=center>Dim 14:20</td><td align=center>Mer 14:20</td><td align=center>Jeu 18:30</td><td align=center>Dim 00:58</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>105</td><td align=center> Andorra</td><td align=center>4</td><td align=center>29</td><td align=center>155</td><td align=center>126</td><td align=center>Dim 15:15</td><td align=center>Mer 15:15</td><td align=center>Ven 06:25</td><td align=center>Sam 01:28</td></tr>
<tr><td align=center>106</td><td align=center> Al Urdun</td><td align=center>4</td><td align=center>7</td><td align=center>77</td><td align=center>70</td><td align=center>Dim 18:40</td><td align=center>Mer 18:40</td><td align=center>Jeu 13:15</td><td align=center>Dim 01:19</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>107</td><td align=center> Guatemala</td><td align=center>4</td><td align=center>81</td><td align=center>140</td><td align=center>59</td><td align=center>Lun 01:10</td><td align=center>Jeu 01:10</td><td align=center>Ven 04:30</td><td align=center>Dim 03:20</td></tr>
<tr><td align=center>110</td><td align=center> Trinidad/T.</td><td align=center>3</td><td align=center>14</td><td align=center>99</td><td align=center>85</td><td align=center>Dim 22:20</td><td align=center>Mer 22:20</td><td align=center>Ven 02:15</td><td align=center>Dim 03:44</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>111</td><td align=center> Nicaragua</td><td align=center>3</td><td align=center>26</td><td align=center>91</td><td align=center>65</td><td align=center>Dim 23:40</td><td align=center>Mer 23:40</td><td align=center>Ven 01:15</td><td align=center>Dim 03:26</td></tr>
<tr><td align=center>112</td><td align=center> Kazakhstan</td><td align=center>4</td><td align=center>96</td><td align=center>119</td><td align=center>23</td><td align=center>Dim 08:00</td><td align=center>Mer 12:10</td><td align=center>Ven 06:04</td><td align=center>Sam 02:24</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>113</td><td align=center> Suriname</td><td align=center>3</td><td align=center>14</td><td align=center>95</td><td align=center>81</td><td align=center>Dim 23:10</td><td align=center>Mer 23:10</td><td align=center>Jeu 23:30</td><td align=center>Dim 03:37</td></tr>
<tr><td align=center>117</td><td align=center> Liechtenst.</td><td align=center>4</td><td align=center>59</td><td align=center>222</td><td align=center>163</td><td align=center>Sam 19:50</td><td align=center>Mar 19:50</td><td align=center>Jeu 05:18</td><td align=center>Sam 01:59</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>118</td><td align=center> Algérie</td><td align=center>5</td><td align=center>64</td><td align=center>95</td><td align=center>31</td><td align=center>Dim 19:25</td><td align=center>Mer 20:10</td><td align=center>Jeu 13:11</td><td align=center>Dim 01:12</td></tr>
<tr><td align=center>119</td><td align=center> Lungol Uls</td><td align=center>3</td><td align=center>5</td><td align=center>89</td><td align=center>84</td><td align=center>Sam 07:50</td><td align=center>Mer 07:50</td><td align=center>Jeu 14:29</td><td align=center>Ven 22:29</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>120</td><td align=center> Lubnan</td><td align=center>4</td><td align=center>22</td><td align=center>89</td><td align=center>67</td><td align=center>Dim 14:40</td><td align=center>Mer 17:40</td><td align=center>Jeu 13:09</td><td align=center>Dim 01:09</td></tr>
<tr><td align=center>121</td><td align=center> Sénégal</td><td align=center>4</td><td align=center>27</td><td align=center>109</td><td align=center>82</td><td align=center>Dim 18:20</td><td align=center>Mer 11:50</td><td align=center>Jeu 11:44</td><td align=center>Sam 04:44</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>122</td><td align=center> Hayastan</td><td align=center>3</td><td align=center>26</td><td align=center>86</td><td align=center>60</td><td align=center>Dim 14:10</td><td align=center>Mer 14:40</td><td align=center>Jeu 18:31</td><td align=center>Dim 00:31</td></tr>
<tr><td align=center>123</td><td align=center> Bahrain</td><td align=center>4</td><td align=center>7</td><td align=center>84</td><td align=center>77</td><td align=center>Dim 16:50</td><td align=center>Mer 16:50</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>124</td><td align=center> Barbados</td><td align=center>3</td><td align=center>7</td><td align=center>90</td><td align=center>83</td><td align=center>Dim 22:10</td><td align=center>Mer 22:10</td><td align=center>Ven 01:45</td><td align=center>Dim 03:43</td></tr>
<tr><td align=center>125</td><td align=center> Cabo Verde</td><td align=center>3</td><td align=center>15</td><td align=center>101</td><td align=center>86</td><td align=center>Dim 18:25</td><td align=center>Mer 18:25</td><td align=center>Jeu 13:15</td><td align=center>Dim 01:12</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>126</td><td align=center> C. d’Ivoire</td><td align=center>3</td><td align=center>30</td><td align=center>114</td><td align=center>84</td><td align=center>Dim 18:55</td><td align=center>Mer 18:55</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:33</td></tr>
<tr><td align=center>127</td><td align=center> Al Kuwayt</td><td align=center>4</td><td align=center>6</td><td align=center>70</td><td align=center>64</td><td align=center>Dim 16:10</td><td align=center>Mer 16:10</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>128</td><td align=center> Al Iraq</td><td align=center>4</td><td align=center>13</td><td align=center>75</td><td align=center>62</td><td align=center>Dim 16:25</td><td align=center>Mer 16:25</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr><td align=center>129</td><td align=center> Az?rbaycan</td><td align=center>4</td><td align=center>94</td><td align=center>126</td><td align=center>32</td><td align=center>Dim 14:25</td><td align=center>Mer 14:25</td><td align=center>Jeu 18:30</td><td align=center>Dim 00:58</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>130</td><td align=center> Angola</td><td align=center>3</td><td align=center>24</td><td align=center>104</td><td align=center>80</td><td align=center>Sam 19:40</td><td align=center>Mar 19:40</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:27</td></tr>
<tr><td align=center>131</td><td align=center> Crna Gora</td><td align=center>4</td><td align=center>113</td><td align=center>159</td><td align=center>46</td><td align=center>Sam 11:55</td><td align=center>Mer 11:55</td><td align=center>Jeu 16:30</td><td align=center>Ven 23:20</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>132</td><td align=center> Bangladesh</td><td align=center>3</td><td align=center>23</td><td align=center>84</td><td align=center>61</td><td align=center>Dim 07:45</td><td align=center>Mer 06:30</td><td align=center>Ven 06:07</td><td align=center>Sam 02:22</td></tr>
<tr><td align=center>133</td><td align=center> Al Yaman</td><td align=center>4</td><td align=center>4</td><td align=center>77</td><td align=center>73</td><td align=center>Dim 16:35</td><td align=center>Mer 16:35</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>134</td><td align=center> Oman</td><td align=center>4</td><td align=center>11</td><td align=center>84</td><td align=center>73</td><td align=center>Dim 16:40</td><td align=center>Mer 16:40</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr><td align=center>135</td><td align=center> Moçambique</td><td align=center>3</td><td align=center>23</td><td align=center>97</td><td align=center>74</td><td align=center>Dim 16:40</td><td align=center>Mer 16:40</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>136</td><td align=center> Brunei</td><td align=center>3</td><td align=center>18</td><td align=center>102</td><td align=center>84</td><td align=center>Dim 05:00</td><td align=center>Mer 05:00</td><td align=center>Ven 08:00</td><td align=center>Sam 01:50</td></tr>
<tr><td align=center>137</td><td align=center> Ghana</td><td align=center>3</td><td align=center>22</td><td align=center>96</td><td align=center>74</td><td align=center>Dim 18:25</td><td align=center>Mer 18:25</td><td align=center>Jeu 13:15</td><td align=center>Dim 01:12</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>138</td><td align=center> Kampuchea</td><td align=center>3</td><td align=center>16</td><td align=center>92</td><td align=center>76</td><td align=center>Sam 08:00</td><td align=center>Mer 05:15</td><td align=center>Jeu 17:15</td><td align=center>Ven 22:30</td></tr>
<tr><td align=center>139</td><td align=center> Bénin</td><td align=center>3</td><td align=center>31</td><td align=center>92</td><td align=center>61</td><td align=center>Dim 18:45</td><td align=center>Mer 11:45</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:33</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>140</td><td align=center> Suriyah</td><td align=center>4</td><td align=center>10</td><td align=center>74</td><td align=center>64</td><td align=center>Dim 16:35</td><td align=center>Mer 16:35</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr><td align=center>141</td><td align=center> Qatar</td><td align=center>4</td><td align=center>14</td><td align=center>95</td><td align=center>81</td><td align=center>Dim 16:10</td><td align=center>Mer 16:10</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>142</td><td align=center> Tanzania</td><td align=center>3</td><td align=center>24</td><td align=center>108</td><td align=center>84</td><td align=center>Dim 12:45</td><td align=center>Mer 11:15</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:44</td></tr>
<tr><td align=center>143</td><td align=center> Uganda</td><td align=center>3</td><td align=center>15</td><td align=center>98</td><td align=center>83</td><td align=center>Dim 16:20</td><td align=center>Mer 16:20</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:18</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>144</td><td align=center> Maldives</td><td align=center>3</td><td align=center>13</td><td align=center>97</td><td align=center>84</td><td align=center>Dim 08:15</td><td align=center>Mer 06:00</td><td align=center>Ven 06:05</td><td align=center>Sam 04:44</td></tr>
<tr><td align=center>145</td><td align=center> Uzbekistan</td><td align=center>3</td><td align=center>16</td><td align=center>89</td><td align=center>73</td><td align=center>Dim 14:30</td><td align=center>Mer 14:30</td><td align=center>Jeu 18:30</td><td align=center>Dim 00:58</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>146</td><td align=center> Cameroon</td><td align=center>3</td><td align=center>9</td><td align=center>91</td><td align=center>82</td><td align=center>Dim 18:55</td><td align=center>Mer 18:55</td><td align=center>Jeu 13:00</td><td align=center>Sam 04:33</td></tr>
<tr><td align=center>147</td><td align=center> Cuba</td><td align=center>3</td><td align=center>34</td><td align=center>119</td><td align=center>85</td><td align=center>Dim 23:15</td><td align=center>Mer 23:15</td><td align=center>Ven 00:50</td><td align=center>Dim 03:25</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>148</td><td align=center> Palestine</td><td align=center>4</td><td align=center>4</td><td align=center>96</td><td align=center>92</td><td align=center>Dim 16:15</td><td align=center>Mer 16:15</td><td align=center>Jeu 13:20</td><td align=center>Dim 00:23</td></tr>
<tr><td align=center>149</td><td align=center> São Tomé e P</td><td align=center>4</td><td align=center>0</td><td align=center>218</td><td align=center>218</td><td align=center>Dim 18:25</td><td align=center>Mer 18:50</td><td align=center>Jeu 13:15</td><td align=center>Sam 04:33</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>151</td><td align=center> Comoros</td><td align=center>4</td><td align=center>0</td><td align=center>186</td><td align=center>186</td><td align=center>Dim 12:45</td><td align=center>Mer 11:10</td><td align=center>Jeu 13:15</td><td align=center>Dim 00:44</td></tr>
<tr><td align=center>152</td><td align=center> Sri Lanka</td><td align=center>4</td><td align=center>7</td><td align=center>182</td><td align=center>175</td><td align=center>Dim 08:15</td><td align=center>Mer 06:45</td><td align=center>Ven 06:05</td><td align=center>Sam 04:44</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>153</td><td align=center> Curaçao</td><td align=center>4</td><td align=center>2</td><td align=center>262</td><td align=center>260</td><td align=center>Dim 22:25</td><td align=center>Mer 22:25</td><td align=center>Ven 06:15</td><td align=center>Dim 03:15</td></tr>
<tr><td align=center>154</td><td align=center> Guam</td><td align=center>4</td><td align=center>9</td><td align=center>180</td><td align=center>171</td><td align=center>Dim 04:15</td><td align=center>Mer 04:15</td><td align=center>Ven 04:15</td><td align=center>Sam 03:15</td></tr>
<tr bgcolor="#EFEFEF"><td align=center>1000</td><td align=center> International</td><td align=center>6</td><td align=center>0</td><td align=center>2449</td><td align=center>2449</td><td align=center>Ven 17:00</td><td align=center>Mar 16:00</td><td align=center>Jeu 10:15</td><td align=center>Ven 13:00</td></tr>
</table>

